name: Deploy Blender Extension Registry

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moguri/setup-blender@v1
        with:
          blender-version: '4.3'
      - run: make
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: './repository/'
      - uses: actions/deploy-pages@v4
